export const FETCH_POSTS_BEGIN = 'FETCH_POSTS_BEGIN';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const FETCH_POSTS_DETAIL_BEGIN = 'FETCH_POSTS_DETAIL_BEGIN';
export const FETCH_POSTS_DETAIL_SUCCESS = 'FETCH_POSTS_DETAIL_SUCCESS';
export const FETCH_POSTS_DETAIL_FAILURE = 'FETCH_POSTS_DETAIL_FAILURE';

export const FETCH_POSTS_AREA_BEGIN = 'FETCH_POSTS_AREA_BEGIN';
export const FETCH_POSTS_AREA_SUCCESS = 'FETCH_POSTS_AREA_SUCCESS';
export const FETCH_POSTS_AREA_FAILURE = 'FETCH_POSTS_AREA_FAILURE';

export const FETCH_DESTINATION_BEGIN = 'FETCH_DESTINATION_BEGIN';
export const FETCH_DESTINATION_SUCCESS = 'FETCH_DESTINATION_SUCCESS';
export const FETCH_DESTINATION_FAILURE = 'FETCH_DESTINATION_FAILURE';

export const FETCH_PACKAGE_BEGIN = 'FETCH_PACKAGE_BEGIN';
export const FETCH_PACKAGE_SUCCESS = 'FETCH_PACKAGE_SUCCESS';
export const FETCH_PACKAGE_FAILURE = 'FETCH_PACKAGE_FAILURE';

export const FETCH_PACKAGE_DETAIL_BEGIN = 'FETCH_PACKAGE_DETAIL_BEGIN';
export const FETCH_PACKAGE_DETAIL_SUCCESS = 'FETCH_PACKAGE_DETAIL_SUCCESS';
export const FETCH_PACKAGE_DETAIL_FAILURE = 'FETCH_PACKAGE_DETAIL_FAILURE';

export const FETCH_PACKAGE_DESTINATION_BEGIN = 'FETCH_PACKAGE_DESTINATION_BEGIN';
export const FETCH_PACKAGE_DESTINATION_SUCCESS = 'FETCH_PACKAGE_DESTINATION_SUCCESS';
export const FETCH_PACKAGE_DESTINATION_FAILURE = 'FETCH_PACKAGE_DESTINATION_FAILURE';

export const SEARCH_TOUR_BEGIN = 'SEARCH_TOUR_BEGIN';
export const SEARCH_TOUR_SUCCESS = 'SEARCH_TOUR_SUCCESS';
export const SEARCH_TOUR_FAILURE = 'SEARCH_TOUR_FAILURE';

export const HANDLE_SUBMIT_FORM_ORDER_BEGIN = 'HANDLE_SUBMIT_FORM_ORDER_BEGIN';
export const HANDLE_SUBMIT_FORM_ORDER_SUCCESS = 'HANDLE_SUBMIT_FORM_ORDER_SUCCESS';
export const HANDLE_SUBMIT_FORM_ORDER_FAILURE = 'HANDLE_SUBMIT_FORM_ORDER_FAILURE';
